export const GET_PRODUCT_REQ = "GET_PRODUCT_REQ";
export const GET_SINGLE_PRODUCT_REQ = "GET_SINGLE_PRODUCT_REQ";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const GET_PRODUCT_CLICKED_REQ = "GET_PRODUCT_CLICKED_REQ";
export const GET_PRODUCT_CLICKED_SUCCESS = "GET_PRODUCT_CLICKED_SUCCESS";
export const GET_PRODUCT_CLICKED_FAILURE = "GET_PRODUCT_CLICKED_FAILURE";

export const FILTER_DATA = "FILTER_DATA";

